# Generated by Django 5.2.4 on 2025-08-07 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Type',
                'verbose_name_plural': 'Home Types',
            },
        ),
        migrations.CreateModel(
            name='ListingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Listing Agent',
                'verbose_name_plural': 'Listing Agents',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.PositiveIntegerField()),
                ('bath', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('sqft', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homes', to='homesapi.hometype')),
                ('listing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='homesapi.listingagent')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_homes', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='homesapi.home')),
            ],
            options={
                'verbose_name': 'Favorite Home',
                'verbose_name_plural': 'Favorite Homes',
                'ordering': ['-created_at'],
                'unique_together': {('home', 'user')},
            },
        ),
    ]
